# Generated by Django 4.1.3 on 2023-01-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRC', '0002_remove_image_price_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images\\profile\\default.png', upload_to='images/profile'),
        ),
    ]
