# Generated by Django 4.1.3 on 2023-01-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRC', '0004_image_author_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
    ]
